name: Feature Request
description: Suggest an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe your idea

  - type: textarea
    attributes:
      label: Alternatives Considered